# Makefile

# Set the name of the Docker image
IMAGE_NAME = static-website

# Set the name of the Nginx container
NGINX_CONTAINER_NAME = my-static-website-container

# Set the relative directory on the host for Certbot
HOST_LETSENCRYPT_DIR = letsencrypt

# Set your domain for Certbot
DOMAIN = fiscaltimeline.com

# Default target: build the Docker image
build:
	docker build -t $(IMAGE_NAME) .

# Target to run the Docker container in the background with ports 443
run:
	docker run -d -p 443:443 --name $(NGINX_CONTAINER_NAME) \
	  -v "$(HOST_LETSENCRYPT_DIR):/etc/letsencrypt" \
	  -v "$(HOST_LETSENCRYPT_DIR):/var/lib/letsencrypt" \
	  $(IMAGE_NAME)

# Target to stop the Nginx container
stop-nginx:
	docker stop $(NGINX_CONTAINER_NAME)

# Target to start the Nginx container
start-nginx:
	docker start $(NGINX_CONTAINER_NAME)

# Target to stop and remove the Docker container
stop:
	docker stop $(NGINX_CONTAINER_NAME)
	docker rm $(NGINX_CONTAINER_NAME)

# Target to clean up the Docker image
clean:
	docker rmi $(IMAGE_NAME)

# Target to obtain or renew SSL certificate using Certbot
certbot:
	docker run -it --rm \
	  -p 80:80 \
	  -v "$(shell pwd)/letsencrypt:/etc/letsencrypt" \
	  -v "$(shell pwd)/letsencrypt:/var/lib/letsencrypt" \
	  certbot/certbot certonly --standalone -d $(DOMAIN)

# Target to update Nginx container with SSL certificate
update-nginx-ssl:
	@if [ $$(docker inspect -f '{{.State.Running}}' my-static-website-container) = "true" ]; then \
	  docker exec my-static-website-container nginx -s reload; \
	else \
	  echo "Nginx container is not running. Please ensure it is running."; \
	fi

# Target to run the Docker container with SSL support
run-ssl:
	@docker stop my-static-website-container || true
	@docker rm my-static-website-container || true
	docker run -d -p 80:80 -p 443:443 --name my-static-website-container \
	  -v "$(shell pwd)/letsencrypt:/etc/letsencrypt" \
	  -v "$(shell pwd)/letsencrypt:/var/lib/letsencrypt" \
	  $(IMAGE_NAME)

# Display steps
steps:
	@echo "Available steps:"
	@echo "  1. make build          - Build the Docker image"
	@echo "  2. make run            - Run the Docker container in the background (HTTP and HTTPS)"
	@echo "  3. make certbot        - Obtain or renew SSL certificate using Certbot"
	@echo "  4. make update-nginx-ssl - Update Nginx container with SSL certificate"
	@echo "  5. make run-ssl        - Run the Docker container with SSL support (HTTPS)"
	@echo "  6. make stop           - Stop and remove the Docker container"
	@echo "  7. make clean          - Clean up the Docker image"
	@echo "  8. make steps          - Display these steps"